EXCHANGE_URL = "http://localhost:8080/"
BOT_USER_ID = -666
MARKET_NAME = "TESTNET3RINKEBY"
MONEY_NAME = "TESTNET3"
STOCK_NAME = "RINKEBY"
TRADE_BALANCE_PRC = 0.1
SPREAD_PRC = 0.1
BTC_ETH_PRICE_URL = "https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=BTC"
